prometheus_job_name: "object"

var_log_vg: rootvg
var_log_lv: var_loglv

certificates_path: /etc/haproxy/
certificates_list: "{{ binds | map(attribute='cert_name') | map('regex_replace', '^',certificates_path)| list }}"

proxy_path: /etc/haproxy/haproxy.cfg

job: "object"
sources:
  - file: /var/log/haproxy/haproxy.log
    expression: '([^\\"]+)([\\"])(?P<method>[A-Z]+)'
    labels:
      - method

firewall_ports:
  - "{{ cache_port }}/tcp"
  - "443/tcp"
  - "9090/tcp"
