---
- name: Get current config
  shell:
    cmd: "ceph config get {{ item.0.service_name }} {{ item.1.key }}"
  failed_when: false
  changed_when: false
  register: current_configuration

- block:
    - name: "set {{ item.1.key }} to {{ item.1.value }} from {{ current_configuration.stdout }}"
      shell:
        cmd: "ceph config set {{ item.0.service_name }} {{ item.1.key }} {{ item.1.value }}"
    - name: Check if config requires a restart
      shell:
        cmd: "ceph config help {{ item.1.key }} | grep 'runtime: false'"
      register: config_update_on_runtime
      failed_when: false
      changed_when: config_update_on_runtime.rc == 0
      when:
        - item.0.notify is defined
        - ( item.0.notify | lower ) != "false"
      notify: "restart {{ item.0.notify | default(item.0.service_name) }}"
  when:
    - ( current_configuration.stdout | lower) != ( item.1.value | lower)
    - item.1.renove is not defined or not item.1.remove
