---
- name: "Get Public Cluser SSH Key"
  shell:
    cmd: cephadm shell -- ceph cephadm get-pub-key > ~/ceph.pub

- name: "Add Key to cloud-user Authorized Keys"
  shell:
    cmd: cat ~/ceph.pub >> /home/cloud-user/.ssh/authorized_keys

- name: "Set SSH User to cloud-user"
  shell:
    cmd: cephadm shell -- ceph cephadm set-user cloud-user
  when: inventory_hostname in groups['bootstraper']
