---
- hosts: ceph-servers
  roles:
    - configure-cloud-user
  become: true
  ignore_unreachable: yes

- hosts: ceph-servers
  strategy: free
  roles:
    - configure-network-nmcli
  become: true

- hosts: ceph-servers
  roles:
    - configure-resolv
    - configure-time
    - configure-custom-dnf
    - configure-lldpad
    - configure-sysctl
    - configure-dmesg
    - check_servers_connectivity
  become: true

- hosts: all
  gather_facts: no
  roles:
    - set-prompt
  become: yes

- hosts: ceph-servers
  serial: 1
  roles:
    - dnf-update-all
  become: true

- hosts: ceph-servers
  tasks:
    - name: "Install Ceph Packages"
      dnf:
        name:
          - podman
          - cephadm
          - ceph-common
  become: true
