---
- hosts: all
  roles:
    - configure-cloud-user
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: qwer1234
  become: yes
  ignore_unreachable: yes

  #- hosts: all
  #  become: true
  #  tasks:
  #    - name: Configure sync interface
  #      shell:
  #        cmd: "nmcli con del {{ team.name }} && nmcli con add type ethernet ifname {{ team.name }} con-name {{ team.name }} ipv4.method {{ team.method | default('manual') }} ipv4.addresses {{ ansible_host | replace('15', '31') }}/24 ipv4.gateway {{ team.gw4 }} ipv4.never-default yes"
  #      loop: "{{ teams }}"
  #      loop_control:
  #        loop_var: team              
  
- hosts: all
  #  pre_tasks:
  #    - name: Configure CA
  #      copy:
  #        src: "{{ item }}"
  #        dest: "{{ item }}"
  #        force: yes
  #      loop:
  #        - /etc/pki/ca-trust/source/anchors/cert.pem
  #        - /etc/pki/ca-trust/extracted/pem/

  roles:
    - configure-resolv
    - configure-data-ca
    - configure-time
    - configure-custom-dnf    
    - configure-lldpad
    - configure-sysctl
    - configure-dmesg
#    - check_servers_connectivity
#    - create-dns-record
  become: true
    
- hosts: all
  gather_facts: no
  roles:
    - set-prompt
  become: yes

- hosts: all
  serial: 1
  roles:
    - dnf-update-all
  become: true

- hosts: ceph-servers
  tasks:
    - name: "Install Ceph Packages"
      dnf:
        name:
          - podman
          - cephadm
          - ceph-common
  become: true
