---
- hosts: bootstraps
  roles: 
    - cephadm-orchestrate
  become: true

- hosts: 
  roles:
    - configure-lvm
  become: true

#- hosts: #prod cache hosts
#  roles:
#    # - configure-rbd-image -> Variables not configured
#    # - configure-service-rbd-usage
#  become: true
  
- hosts: caches
  roles:
    - configure-nginx-cache
    - configure-keepalive
  tags: 
    - configure-cache
  become: true

- hosts: mgmt-proxies
  roles:
    - routes
  ignore_unreachable: yes

- hosts: proxies
  roles:
    - configure-object-proxy
    - configure-keepalive
  tags: 
    - configure-proxy
  become: true

- hosts: caches,proxies
  roles:
    - configure-firewalld
  become: true
