---
- hosts: bootstraps
  roles: 
    - cephadm-orchestrate
  become: true

- hosts: mgmt-proxies
  roles:
    - routes
  ignore_unreachable: yes

- hosts: proxies
  roles:
    - configure-object-proxy
    - configure-keepalive
  tags: 
    - configure-proxy
  become: true

- hosts: caches,proxies
  roles:
    - configure-firewalld
  become: true
